
environment:

    matrix:
        - TOXENV: py35
        - TOXENV: py36
        - TOXENV: py37


install:
    - python --version
    - pip list
    - dir

build: off


test_script:
    - pip install --disable-pip-version-check fastfilepackage --upgrade


on_finish:
    - python --version
    - pip list
    - dir
